#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Dumeng-cong 的技术博客

# Short bio or description (displayed in the header)
description: Dumeng-cong的个人技术博客，分享学习笔记、项目实践与思考。

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/xiyangyang.jpg


#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  # dribbble: # 如果有Dribbble，请填写用户名
  email: 3202944144@qq.com # 已启用邮箱，请确保格式正确
  # facebook: # 如果有Facebook，请填写你的用户名
  # flickr: # 如果有Flickr，请填写用户名
  github: Dumeng-cong # **重要：已更正为GitHub用户名**
  # instagram: # 如果有Instagram，请填写用户名
  # linkedin: # 如果有LinkedIn，请填写个人主页URL的最后一部分，eg："in/yourname/"
  # pinterest: # 如果有Pinterest，请填写用户名
  rss: true # 已更正，启用RSS图标
  # twitter: # 如果有Twitter，请填写用户名
  # stackoverflow: # 你的Stack Overflow profile, e.g. "users/50476/bart-kiers"
  # youtube: # channel/<your_long_string> or user/<user-name>
  # googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# disqus: dumeng-cong-blog # 已禁用Disqus，因为国内访问问题

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# google_analytics: UA-XXXXXXXX-X # 如果需要Google Analytics，请填写ID

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://Dumeng-cong.github.io # **重要：GitHub Pages网站地址**

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "" # 对于用户页面（yourusername.github.io），这里保持为空
baseurl: "/Dumeng-cong.github.io"


#
# !! You don't need to change any of the configuration flags below !!
#
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

